[env:t5_epaper_s3_defaultui]
extends = esp32s3_base
board = esp32s3box
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.partitions = default_16MB.csv
build_src_filter =
  ${esp32s3_base.build_src_filter}
  +<../variants/esp32s3/diy/t5_epaper_s3_defaultui>
build_flags = 
  ${esp32s3_base.build_flags}
  -D PRIVATE_HW
  -D BOARD_HAS_PSRAM
  -D USE_EINK
  -D USE_EINK_EPDIY
  -D EINK_WIDTH=960
  -D EINK_HEIGHT=540
  -D HAS_TOUCHSCREEN=1
  -D SCREEN_TOUCH_INT=3
  -I variants/esp32s3/diy/t5_epaper_s3_defaultui
lib_deps =
  https://github.com/ITJesse/epdiy-t5s3.git#t5s3-pro
  lewisxhe/SensorLib@0.3.4
  ${esp32s3_base.lib_deps}
  # renovate: datasource=git-refs depName=BQ27220 packageName=https://github.com/mverch67/BQ27220 gitBranch=main
  https://github.com/mverch67/BQ27220/archive/07d92be846abd8a0258a50c23198dac0858b22ed.zip
