[env:t5_epaper_s3]
extends = esp32s3_base
board = t5_epaper_s3_pro
build_src_filter =
  ${esp32s3_base.build_src_filter}
  +<../variants/esp32s3/diy/t5_epaper_s3>
build_flags = 
  ${esp32s3_base.build_flags}
  -D PRIVATE_HW
  -D USE_EINK
  -D USE_EINK_EPDIY
  -D EINK_WIDTH=960
  -D EINK_HEIGHT=540
  -D HAS_TOUCHSCREEN=1
  -D SCREEN_TOUCH_INT=3
  -ULED_BUILTIN
  -D MESHTASTIC_EXCLUDE_PAXCOUNTER
  -I variants/esp32s3/diy/t5_epaper_s3
  -I"${platformio.packages_dir}/framework-arduinoespressif32/tools/sdk/esp32s3/include/esp_rom/include/esp32s3/rom"
  -I"${platformio.packages_dir}/framework-arduinoespressif32/tools/sdk/esp32s3/include/esp_rom/include"
lib_deps =
  https://github.com/vroland/epdiy.git
  lewisxhe/SensorLib@0.3.4
  ${esp32s3_base.lib_deps}
  # renovate: datasource=git-refs depName=BQ27220 packageName=https://github.com/mverch67/BQ27220 gitBranch=main
  https://github.com/mverch67/BQ27220/archive/07d92be846abd8a0258a50c23198dac0858b22ed.zip
