[env:t5_epaper_s3]
extends = esp32s3_base, inkhud
board = t5_epaper_s3_pro
build_src_filter =
  ${esp32s3_base.build_src_filter}
  ${inkhud.build_src_filter}
  +<../variants/esp32s3/diy/t5_epaper_s3>
build_flags = 
  ${esp32s3_base.build_flags}
  ${inkhud.build_flags}
  -D PRIVATE_HW
  -I variants/esp32s3/diy/t5_epaper_s3
lib_deps =
  https://github.com/ITJesse/epdiy-t5s3.git#t5s3-pro
  ${inkhud.lib_deps}
  ${esp32s3_base.lib_deps}
  # renovate: datasource=git-refs depName=BQ27220 packageName=https://github.com/mverch67/BQ27220 gitBranch=main
  https://github.com/mverch67/BQ27220/archive/07d92be846abd8a0258a50c23198dac0858b22ed.zip
